apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pvc
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: Wordpress用Snapshot
spec:
  accessModes:
     - ReadWriteMany
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 1Gi
